[package]
name = "study"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# web-socket库官网 https://github.com/snapview/tokio-tungstenite
tokio-tungstenite = "0.17.2"