[package]
name = "salvo-web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# web依赖
salvo = { version= "*" }
tokio = { version = "1", features = ["macros"] }